services:

  laravel-docker:
    container_name: laravel-docker
    restart: always
    build: .
    volumes:
      - ./laravel-app/:/var/www/html
    ports:
      - 9001:80
  
  mysql_db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: egls_db
    ports:
    - 3307:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 9002:80
    environment:
      - PMA_PORT:3307
      - PMA_ARBITRARY=1
